export const GlobalImages = {
    LG_TELPRO: require("../../assets/images/Logo_Telpro.png"),
    IMG_ACCOUNTDEFAULT: require("../../assets/images/account1.jpg"),
    BG_CAPTCHA: require("../../assets/images/captcha_background.png"),
    BG_HEAD_MODAL: require("../../assets/images/bg_header_modal.png"),
    IMG1: require("../../assets/images/image1.jpg"),
    IMG2: require("../../assets/images/image2.jpg"),
    IMG3: require("../../assets/images/image3.jpg"),
    IMG4: require("../../assets/images/image4.jpg"),
    IMG5: require("../../assets/images/image5.jpg"),
    IMGCUTI: require("../../assets/images/sunbed.png"),
    IMGABSEN: require("../../assets/images/absentism.png"),
    IMGLEMBUR: require("../../assets/images/overwork.png"),
    IMGLOGO: require("../../assets/images/rastek-removebg-preview.png"),
    IMG_UNDERCONSTRUCTION: require("../../assets/images/under_construction.png"),
    IMGLOGOUT: require("../../assets/images/logout.png"),
}